name: LobbyPvP
version: '1.0.0'
main: me.claude.lobbypvp.LobbyPvPPlugin
api-version: '1.21'
authors: [ Smith, CEO-Asooner ]
softdepend: [ ajParkour ]
description: Gives players a fully-configurable PvP kit in the lobby, with a toggle-by-holding system, right-click ability and kill effects.

commands:
  lobbypvp:
    aliases: [ hubpvp, lpvp ]
    description: LobbyPvP core command.
    usage: /lobbypvp reload
    permission: lobbypvp.reload

permissions:
  lobbypvp.reload:
    description: Allows reloading the LobbyPvP configuration.
    default: op
  lobbypvp.bypass:
    description: Bypasses the lobby PvP restrictions (won't be given a kit / can't be attacked).
    default: op
